"""Generate v5e_port.py: the kept v5e cases, from the frozen v5e runner's registrations.

Revision 11 (GAP-37) declares `rev11/v5e_cases_kept.json` and "the named registrations of the frozen
v5e runner" spec data. Each kept, changed or ported row is run "with its v5f_outcome,
v5f_sub_assertions and v5f_placement, reading its shape from the named v5e section or runner
registration". This script copies those registrations (and the fixtures and helpers they use) from
papers/first-afference/run_protocol_v5e.py, checked by sha256, applies the port table below, and
writes v5f_exam/v5e_port.py. Nothing is chosen here: each replacement is a rule of revision 11's
data file, or plumbing that binds the v5f implementation under test in place of styxx.protocol.

Usage: python tools/gen_v5e_port.py [--check]     (--check: exit 1 if v5e_port.py would change)
"""
import hashlib, os, sys

EXAM = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(os.path.dirname(EXAM), "run_protocol_v5e.py")
OUT = os.path.join(EXAM, "v5e_port.py")
SRC_SHA256 = "ef4b4f668bca0b8f72b500dd103d0318786f7e5fc2916b1250f9926287ea3f52"

HEADER = '''# -*- coding: utf-8 -*-
"""GENERATED by tools/gen_v5e_port.py from papers/first-afference/run_protocol_v5e.py
(sha256 {sha}). Do not edit by hand: re-run the generator.

The frozen v5e runner's case registrations, fixtures and helpers (spec data under revision 11,
GAP-37), bound to the v5f implementation under test by bind(). The port table the generator
applied is listed in tools/gen_v5e_port.py (PORT).
"""
from __future__ import annotations

import asyncio
import dataclasses
import functools
import gc
import importlib
import importlib.machinery
import importlib.util
import json
import os
import queue
import random
import re
import sched
import shutil
import signal
import subprocess
import sys
import tempfile
import threading
import time
import traceback
import types
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent    # papers/first-afference (the v5e runner's HERE)
ROOT = HERE.parent.parent
P = Experiment = GateSpecError = _select_gates_block = coverage_trace = None
MUTATION = False
P1_PREREG = "PREREG_p1_power_refusal_2026_08_08.md"
FIXED_SENTENCE = ("work on other threads, pools, executors or asyncio tasks is credited only to a "
                  "section that work opens itself")
NE_WORDING = "not executed on the stack of any opening of section"
_GETREFCOUNT, _GET_REFERRERS = sys.getrefcount, gc.get_referrers


def bind(impl):
    """Bind the v5f implementation under test where the v5e runner imported styxx.protocol."""
    global P, Experiment, GateSpecError, _select_gates_block, coverage_trace
    P = impl
    Experiment, GateSpecError = impl.Experiment, impl.GateSpecError
    _select_gates_block, coverage_trace = impl._select_gates_block, impl.coverage_trace


# Port table, "A v5e sub-assertion that reads a private name of styxx.protocol reads _v5_state()
# instead": the v5e registries become the v5f machinery state.
def _registries():
    st = dict(P._v5_state())
    st.pop("pid", None)
    for k in ("cut", "tool", "tool_ours"):
        st.pop(k, None)
    return st


def _registries_equal(before) -> bool:
    return _registries() == before


def _hazard_clean(fx) -> str | None:
    """H3's per-trial leftover (v5f outcome: 'leaves no profile or trace function behind (v5f has
    none to leave)'): no profile or trace function, the machinery quiet, f's __code__ restored."""
    bad = []
    if sys.getprofile() is not None:
        bad.append(f"profiler {{sys.getprofile()!r}}")
    if sys.gettrace() is not None:
        bad.append(f"trace function {{sys.gettrace()!r}}")
    st = P._v5_state()
    if st["mints"] or st["anchors"] or st["global_events"]:
        bad.append(f"machinery not quiet: mints {{len(st['mints'])}}, anchors {{st['anchors']}}, "
                   f"global_events {{st['global_events']}}")
    if fx.f.__code__ is not _HAZ_CODES.get("f", fx.f.__code__):
        bad.append("f.__code__ not restored")
    return "; ".join(bad) or None


_HAZ_CODES: dict = {{}}

'''

# (start marker, end marker): copied verbatim, end exclusive
REGIONS = [
    ("FX, OTHER, DEC, REEXP, LAZY = ", "# -- the P1 harness"),
    ("# -- the P1 harness", "# -- plumbing"),
    ("# -- plumbing", "# -- violation cases"),
    ("# -- violation cases", "# -- the case runner (A1, A8)"),
    ("H_SIGNAL_MAX_S = ", "H1_SITES = "),
]

# The port table: (why, old, new). Each old text must occur exactly once in the copied regions.
PORT = [
    ("P1 harness: `from styxx.power import` needs a `styxx` package; a bare package module stands in "
     "so that importing styxx.power does not import styxx/__init__.py (which imports the v5e "
     "implementation). styxx.power itself is loaded exactly as v5e loads it",
     '    loader = importlib.machinery.SourceFileLoader("styxx.power", str(path))\n',
     '    if "styxx" not in sys.modules:\n'
     '        pkg = types.ModuleType("styxx")\n'
     '        pkg.__path__ = [str(ROOT / "styxx")]\n'
     '        sys.modules["styxx"] = pkg\n'
     '    loader = importlib.machinery.SourceFileLoader("styxx.power", str(path))\n'),
    ("V26 (changed): v5f_outcome '{f:1}, no note' (PROFILER_LOST is retired)",
     '        return _expect(exp, rec, {"G": {T("f"): 1}}, notes={"G": ["PROFILER_LOST"]})\n',
     '        return _expect(exp, rec, {"G": {T("f"): 1}})\n'),
    ("V27 (kept): v5f_sub_assertions 'no note (v5e allowed PROFILER_LOST; v5f has none)'",
     '        return _expect(exp, _trace(exp, h), {"G": {T("f"): 1}}, maybe_notes={"G": ["PROFILER_LOST"]})\n',
     '        return _expect(exp, _trace(exp, h), {"G": {T("f"): 1}})\n'),
    ("V28 (changed): v5f_outcome '{f:1}, no note' (THREAD_HOP is retired)",
     '        return _expect(exp, _trace(exp, h), {"G": {T("f"): 1}}, notes={"G": ["THREAD_HOP"]})\n',
     '        return _expect(exp, _trace(exp, h), {"G": {T("f"): 1}})\n'),
]


def build():
    raw = open(SRC, "rb").read()
    sha = hashlib.sha256(raw).hexdigest()
    src = raw.decode("utf-8")
    parts = []
    for a, b in REGIONS:
        i = src.index(a)
        j = src.index(b, i)
        parts.append(src[i:j])
    body = "\n".join(parts)
    for why, old, new in PORT:
        assert body.count(old) == 1, (why, old)
        body = body.replace(old, new)
    return sha, HEADER.format(sha=sha) + body


def main(argv):
    sha, text = build()
    if SRC_SHA256 != "__FILL__" and sha != SRC_SHA256:
        raise SystemExit(f"run_protocol_v5e.py changed: sha256 {sha}, frozen {SRC_SHA256}")
    if "--check" in argv:
        same = os.path.exists(OUT) and open(OUT, encoding="utf-8").read() == text
        print("v5e_port.py: " + ("reproduced" if same else "DIFFERS"))
        return 0 if same else 1
    open(OUT, "w", encoding="utf-8").write(text)
    print(f"wrote {OUT} from run_protocol_v5e.py sha256 {sha}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
